http:
  port: 8080

admin:
  port: 9876
  host: localhost

apiEndpoints:
  deployment:
    host: 'localhost'
    paths: ['/deployment']

serviceEndpoints:
  deployment-server:
    url: 'http://localhost:8081'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  deployment-server:
    apiEndpoints:
      - deployment
    policies:
      - key-auth:
          - action: {}
      - proxy:
          - action:
              serviceEndpoint: deployment-server
              changeOrigin: true
              stipPath: false