version: "3"

services:
  upload-server:
    container_name: upload-server
    build:
      context: .
      dockerfile: ./apps/upload-server/Dockerfile
    restart: always
    environment:
      - PORT=8082
      - FRONTEND_URL=http://localhost:8080
    ports:
      - 8082:8082