version: "3"

services:
  uploader:
    container_name: uploader
    build:
      context: .
      dockerfile: ./apps/uploader/Dockerfile
    restart: always
    environment:
      - SECRET_ACCESS_KEY=test
      - ACCESS_KEY_ID=test
      - REGION=us-east-1
      - S3_BUCKET=rolt
      - S3_ENDPOINT=http://s3.localhost.localstack.cloud:4566