apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vite-ingress
spec:
  rules:
    - host: 'project.localhost'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vite-service
                port:
                  number: 3000
